[build]
  publish = "dist"
  command = "pnpm build"

[functions]
  directory = "api"
  node_bundler = "esbuild"

[dev]
  command = "pnpm dev:web"
  port = 8888
  targetPort = 5173


# API Routes - these redirects should now point to /.netlify/functions/
# Enhanced Agentic AI API Routes
[[redirects]]
  from = "/api/process-changes-enhanced"
  to = "/.netlify/functions/process-changes-enhanced"
  status = 200

[[redirects]]
  from = "/api/process-changes-enhanced/:sessionId"
  to = "/.netlify/functions/process-changes-enhanced/:sessionId"
  status = 200

[[redirects]]
  from = "/api/session/:sessionId"
  to = "/.netlify/functions/get-session?sessionId=:sessionId"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

# Web App API Routes
[[redirects]]
  from = "/api/init"
  to = "/.netlify/functions/web-init"
  status = 200

[[redirects]]
  from = "/api/templates"
  to = "/.netlify/functions/web-templates"
  status = 200

[[redirects]]
  from = "/api/env-status"
  to = "/.netlify/functions/web-env-status"
  status = 200

[[redirects]]
  from = "/api/status"
  to = "/.netlify/functions/web-status"
  status = 200

[[redirects]]
  from = "/api/mongodb-projects"
  to = "/.netlify/functions/mongodb-projects"
  status = 200

[[redirects]]
  from = "/api/develop"
  to = "/.netlify/functions/web-develop"
  status = 200

[[redirects]]
  from = "/api/github-accounts"
  to = "/.netlify/functions/github-accounts"
  status = 200

[[redirects]]
  from = "/api/init/:sessionId"
  to = "/.netlify/functions/web-init/:sessionId"
  status = 200

[[redirects]]
  from = "/api/initialize-project"
  to = "/.netlify/functions/initialize-project"
  status = 200

[[redirects]]
  from = "/api/initialize-project/:sessionId"
  to = "/.netlify/functions/initialize-project/:sessionId"
  status = 200

# Logs page routes - redirect to the Vite app with session parameter
[[redirects]]
  from = "/logs/:sessionId"
  to = "/?session=:sessionId"
  status = 200

[[redirects]]
  from = "/logs"
  to = "/"
  status = 200

# Default redirect for SPA-like behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

