[build]
  publish = "public"
  functions = "api"

[functions]
  directory = "api"

# API Routes - these redirects should now point to /.netlify/functions/
[[redirects]]
  from = "/api/process-changes"
  to = "/.netlify/functions/process-changes"
  status = 200

[[redirects]]
  from = "/api/process-changes/:sessionId"
  to = "/.netlify/functions/process-changes/:sessionId"
  status = 200

[[redirects]]
  from = "/api/session/:sessionId"
  to = "/.netlify/functions/get-session?sessionId=:sessionId"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

# Web App API Routes
[[redirects]]
  from = "/api/init"
  to = "/.netlify/functions/web-init"
  status = 200

[[redirects]]
  from = "/api/templates"
  to = "/.netlify/functions/web-templates"
  status = 200

[[redirects]]
  from = "/api/env-status"
  to = "/.netlify/functions/web-env-status"
  status = 200

[[redirects]]
  from = "/api/status"
  to = "/.netlify/functions/web-status"
  status = 200

# Logs page routes
[[redirects]]
  from = "/logs/:sessionId"
  to = "/logs.html?session=:sessionId"
  status = 200

[[redirects]]
  from = "/logs"
  to = "/logs.html"
  status = 200

# Default redirect for SPA-like behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  functions = "api"
  port = 8888
  framework = "#static"